FROM python:3.11.0b3-slim-buster as builder

WORKDIR /usr/src/app

RUN apt-get update \
  && apt-get clean \
  && apt-get -y install libpq-dev curl build-essential tdsodbc unixodbc

RUN uname -a

COPY openssl.cnf /etc/ssl/openssl.cnf

RUN apt-get update && apt-get install -y curl apt-transport-https \
  && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
  && curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list \
  && apt-get update \
  && ACCEPT_EULA=Y apt-get install -y msodbcsql17 unixodbc-dev

# install SQL Server tools
RUN ACCEPT_EULA=Y apt-get -y install mssql-tools
RUN echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
RUN /bin/bash -c "source ~/.bashrc"


COPY requirements.txt /tmp/requirements.txt

RUN pip install pip --upgrade && pip install -r /tmp/requirements.txt
RUN pwd

COPY . ./